apiVersion: v1
kind: Pod
metadata:
  name: kaniko-scribe
  namespace: holm
spec:
  restartPolicy: Never
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  initContainers:
  - name: git-clone
    image: public.ecr.aws/docker/library/alpine:latest
    command: ["/bin/sh", "-c"]
    args:
    - |
      apk add --no-cache git
      git clone https://github.com/timholm/HolmOS.git /tmp/repo
      cp -r /tmp/repo/services/scribe/* /workspace/
      ls -la /workspace/
    volumeMounts:
    - name: workspace
      mountPath: /workspace
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--dockerfile=/workspace/Dockerfile"
    - "--context=dir:///workspace"
    - "--destination=registry.holm.svc.cluster.local:5000/scribe:latest"
    - "--insecure"
    - "--skip-tls-verify"
    volumeMounts:
    - name: workspace
      mountPath: /workspace
  volumes:
  - name: workspace
    emptyDir: {}
