apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: rpi-4
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2026-01-19T23:38:33Z"
    deletionGracePeriodSeconds: 0
    deletionTimestamp: "2026-01-25T01:43:09Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: keycloak-db
    name: data-keycloak-db-0
    namespace: keycloak
    resourceVersion: "7972"
    uid: 0bfeaf72-27c3-4584-a4e2-024ee1aa6677
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-0bfeaf72-27c3-4584-a4e2-024ee1aa6677
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
