apiVersion: v1
items:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"name":"keycloak","namespace":"keycloak"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"keycloak"}},"serviceName":"keycloak","template":{"metadata":{"labels":{"app":"keycloak"}},"spec":{"containers":[{"args":["start","--http-enabled=true","--proxy-headers=xforwarded","--hostname=https://holm.chat/auth","--hostname-backchannel-dynamic=true"],"env":[{"name":"KC_BOOTSTRAP_ADMIN_USERNAME","valueFrom":{"secretKeyRef":{"key":"KC_BOOTSTRAP_ADMIN_USERNAME","name":"keycloak-secret"}}},{"name":"KC_BOOTSTRAP_ADMIN_PASSWORD","valueFrom":{"secretKeyRef":{"key":"KC_BOOTSTRAP_ADMIN_PASSWORD","name":"keycloak-secret"}}},{"name":"KC_DB","value":"postgres"},{"name":"KC_DB_URL_HOST","value":"keycloak-db"},{"name":"KC_DB_USERNAME","value":"keycloak"},{"name":"KC_DB_PASSWORD","value":"keycloak123"},{"name":"KC_HEALTH_ENABLED","value":"true"},{"name":"KC_HTTP_RELATIVE_PATH","value":"/auth"}],"image":"quay.io/keycloak/keycloak:26.0","livenessProbe":{"httpGet":{"path":"/auth/health/live","port":9000},"initialDelaySeconds":60,"periodSeconds":30},"name":"keycloak","ports":[{"containerPort":8080,"name":"http"}],"readinessProbe":{"httpGet":{"path":"/auth/health/ready","port":9000},"initialDelaySeconds":30,"periodSeconds":10}}]}}}}
    creationTimestamp: "2026-01-19T23:38:33Z"
    generation: 6
    name: keycloak
    namespace: keycloak
    resourceVersion: "10318"
    uid: 05559e8e-32de-4b48-b8d0-d99611d71eba
  spec:
    persistentVolumeClaimRetentionPolicy:
      whenDeleted: Retain
      whenScaled: Retain
    podManagementPolicy: OrderedReady
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: keycloak
    serviceName: keycloak
    template:
      metadata:
        labels:
          app: keycloak
      spec:
        containers:
        - args:
          - start
          - --http-enabled=true
          - --proxy-headers=xforwarded
          - --hostname=https://holm.chat/auth
          - --hostname-backchannel-dynamic=true
          env:
          - name: KC_BOOTSTRAP_ADMIN_USERNAME
            valueFrom:
              secretKeyRef:
                key: KC_BOOTSTRAP_ADMIN_USERNAME
                name: keycloak-secret
          - name: KC_BOOTSTRAP_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: KC_BOOTSTRAP_ADMIN_PASSWORD
                name: keycloak-secret
          - name: KC_DB
            value: postgres
          - name: KC_DB_URL_HOST
            value: keycloak-db
          - name: KC_DB_USERNAME
            value: keycloak
          - name: KC_DB_PASSWORD
            value: keycloak123
          - name: KC_HEALTH_ENABLED
            value: "true"
          - name: KC_HTTP_RELATIVE_PATH
            value: /auth
          - name: KC_HOSTNAME_STRICT
            value: "false"
          - name: KC_HOSTNAME_STRICT_BACKCHANNEL
            value: "false"
          - name: KC_HOSTNAME_URL
            value: https://holm.chat/auth
          - name: KC_PROXY_HEADERS
            value: xforwarded
          - name: KC_HTTP_ENABLED
            value: "true"
          image: quay.io/keycloak/keycloak:26.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /auth/health/live
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: keycloak
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /auth/health/ready
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    updateStrategy:
      rollingUpdate:
        partition: 0
      type: RollingUpdate
  status:
    availableReplicas: 1
    collisionCount: 0
    currentReplicas: 1
    currentRevision: keycloak-84c885fd47
    observedGeneration: 6
    readyReplicas: 1
    replicas: 1
    updateRevision: keycloak-84c885fd47
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
