apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: odoo:/PersistentVolumeClaim:odoo/odoo-data
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"odoo:/PersistentVolumeClaim:odoo/odoo-data"},"name":"odoo-data","namespace":"odoo"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"5Gi"}},"storageClassName":"local-path"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: openmediavault
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2026-01-24T23:36:04Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: odoo-data
    namespace: odoo
    resourceVersion: "7983"
    uid: 4328ea86-0a30-4845-9cfd-036b7cabd034
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-4328ea86-0a30-4845-9cfd-036b7cabd034
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"odoo-data-qnap","namespace":"odoo"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"5Gi"}},"storageClassName":"qnap-iscsi"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: csi.trident.qnap.io
      volume.kubernetes.io/storage-provisioner: csi.trident.qnap.io
    creationTimestamp: "2026-01-25T01:45:43Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: odoo-data-qnap
    namespace: odoo
    resourceVersion: "7984"
    uid: 17dfc94b-3def-4efe-9faa-eb8761dfc59f
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: qnap-iscsi
    volumeMode: Filesystem
    volumeName: pvc-17dfc94b-3def-4efe-9faa-eb8761dfc59f
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: odoo:/PersistentVolumeClaim:odoo/odoo-postgres-data
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"odoo:/PersistentVolumeClaim:odoo/odoo-postgres-data"},"name":"odoo-postgres-data","namespace":"odoo"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"5Gi"}},"storageClassName":"local-path"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: openmediavault
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2026-01-24T23:36:04Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: odoo-postgres-data
    namespace: odoo
    resourceVersion: "7985"
    uid: 67b9e841-fb92-45f9-8638-b38c686ac58d
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-67b9e841-fb92-45f9-8638-b38c686ac58d
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"odoo-postgres-data-qnap","namespace":"odoo"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"5Gi"}},"storageClassName":"qnap-iscsi"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: csi.trident.qnap.io
      volume.kubernetes.io/storage-provisioner: csi.trident.qnap.io
    creationTimestamp: "2026-01-25T01:45:43Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: odoo-postgres-data-qnap
    namespace: odoo
    resourceVersion: "7986"
    uid: ef51ad0b-778f-426c-9571-08c36b5abbff
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: qnap-iscsi
    volumeMode: Filesystem
    volumeName: pvc-ef51ad0b-778f-426c-9571-08c36b5abbff
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
