apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"workflow-artifacts","namespace":"argo"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"5Gi"}},"storageClassName":"nfs-client"}}
    creationTimestamp: "2026-01-22T03:01:01Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: workflow-artifacts
    namespace: argo
    resourceVersion: "7919"
    uid: c18c1e74-8eb2-4a66-b5cc-6dc5f9d34676
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
    storageClassName: nfs-client
    volumeMode: Filesystem
  status:
    phase: Pending
kind: List
metadata:
  resourceVersion: ""
