apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kaniko-workspace
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-cluster
  resources:
    requests:
      storage: 1Gi
