apiVersion: apps/v1
kind: Deployment
metadata:
  name: alice-bot
  namespace: holm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alice-bot
  template:
    metadata:
      labels:
        app: alice-bot
    spec:
      initContainers:
      - name: git-clone
        image: alpine/git:latest
        command: ["sh", "-c"]
        args:
        - |
          git clone --depth 1 https://github.com/timholm/HolmOS.git /repo
          echo "Cloned $(ls /repo/services | wc -l) services"
        volumeMounts:
        - name: repo
          mountPath: /repo
      containers:
      - name: alice-bot
        image: registry.holm.svc.cluster.local:5000/alice-bot:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: REPO_PATH
          value: "/repo"
        volumeMounts:
        - name: repo
          mountPath: /repo
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: repo
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: alice-bot
  namespace: holm
spec:
  type: NodePort
  selector:
    app: alice-bot
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30669
