apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"bookforge-data","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"local-path"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: rpi-2
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2026-01-19T13:51:33Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: bookforge-data
    namespace: default
    resourceVersion: "7920"
    uid: 517ff6e9-6eeb-42cc-9b82-df7e3d0a7657
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-517ff6e9-6eeb-42cc-9b82-df7e3d0a7657
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: holmos:/PersistentVolumeClaim:default/kaniko-workspace
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"holmos:/PersistentVolumeClaim:default/kaniko-workspace"},"name":"kaniko-workspace","namespace":"default"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"nfs-cluster"}}
    creationTimestamp: "2026-01-27T03:22:23Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: kaniko-workspace
    namespace: default
    resourceVersion: "7921"
    uid: 348d908d-5b98-4018-a1ee-57eb936fb8af
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
    storageClassName: nfs-cluster
    volumeMode: Filesystem
  status:
    phase: Pending
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"nas-explorer","namespace":"default"},"spec":{"accessModes":["ReadOnlyMany"],"resources":{"requests":{"storage":"1Ti"}},"storageClassName":"","volumeName":"nas-explorer-pv"}}
      pv.kubernetes.io/bind-completed: "yes"
    creationTimestamp: "2026-01-19T04:18:14Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: nas-explorer
    namespace: default
    resourceVersion: "7922"
    uid: 8ec0961a-3d85-4169-80c2-37ed6b942e9c
  spec:
    accessModes:
    - ReadOnlyMany
    resources:
      requests:
        storage: 1Ti
    storageClassName: ""
    volumeMode: Filesystem
    volumeName: nas-explorer-pv
  status:
    accessModes:
    - ReadOnlyMany
    capacity:
      storage: 1Ti
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"postgres-data","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"5Gi"}},"storageClassName":"local-path"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: openmediavault
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2026-01-19T22:20:25Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: postgres-data
    namespace: default
    resourceVersion: "7923"
    uid: c3a7f9f4-a185-480b-bd8f-22d2f31f1c85
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-c3a7f9f4-a185-480b-bd8f-22d2f31f1c85
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"qnap-test-pvc","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"qnap-iscsi"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: csi.trident.qnap.io
      volume.kubernetes.io/storage-provisioner: csi.trident.qnap.io
    creationTimestamp: "2026-01-25T00:34:33Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: qnap-test-pvc
    namespace: default
    resourceVersion: "7924"
    uid: a8370128-fa6d-4b7b-a8a7-9ad4b725e663
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: qnap-iscsi
    volumeMode: Filesystem
    volumeName: pvc-a8370128-fa6d-4b7b-a8a7-9ad4b725e663
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"test-qnap-pvc","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"qnap-iscsi"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: csi.trident.qnap.io
      volume.kubernetes.io/storage-provisioner: csi.trident.qnap.io
    creationTimestamp: "2026-01-25T01:09:37Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: test-qnap-pvc
    namespace: default
    resourceVersion: "7925"
    uid: 780edc4a-0790-4aaa-818d-9898a878543a
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: qnap-iscsi
    volumeMode: Filesystem
    volumeName: pvc-780edc4a-0790-4aaa-818d-9898a878543a
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: vaultwarden:/PersistentVolumeClaim:default/vaultwarden-data
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"vaultwarden:/PersistentVolumeClaim:default/vaultwarden-data"},"name":"vaultwarden-data","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"local-path"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: rpi-12
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2026-01-20T10:33:26Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: vaultwarden-data
    namespace: default
    resourceVersion: "7926"
    uid: 4510c18e-d982-40c4-b6e4-ce17c038eca9
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-4510c18e-d982-40c4-b6e4-ce17c038eca9
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
