apiVersion: v1
kind: Pod
metadata:
  name: kaniko-health-agg
  namespace: default
spec:
  restartPolicy: Never
  initContainers:
  - name: git-clone
    image: alpine/git:latest
    command:
    - /bin/sh
    - -c
    - |
      git clone --depth 1 https://github.com/timholm/HolmOS.git /workspace/repo
      cp -r /workspace/repo/services/health-agg/* /workspace/
      ls -la /workspace/
    volumeMounts:
    - name: workspace
      mountPath: /workspace
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - --dockerfile=/workspace/Dockerfile
    - --context=/workspace
    - --destination=registry.holm.svc.cluster.local:5000/health-agg:latest
    - --insecure
    - --skip-tls-verify
    volumeMounts:
    - name: workspace
      mountPath: /workspace
  volumes:
  - name: workspace
    emptyDir: {}
