apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: searxng:/PersistentVolumeClaim:searxng/searxng-config
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: csi.trident.qnap.io
      volume.kubernetes.io/storage-provisioner: csi.trident.qnap.io
    creationTimestamp: "2026-01-20T07:53:02Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/instance: searxng
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: searxng
      app.kubernetes.io/version: latest
      helm.sh/chart: searxng-1.0.1
    name: searxng-config
    namespace: searxng
    resourceVersion: "7989"
    uid: 8a43d8f2-ce19-4dd5-a80f-3ec5a492edd7
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: qnap-iscsi
    volumeMode: Filesystem
    volumeName: pvc-8a43d8f2-ce19-4dd5-a80f-3ec5a492edd7
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
