apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: jellyfin:/PersistentVolumeClaim:jellyfin/jellyfin-config
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"jellyfin:/PersistentVolumeClaim:jellyfin/jellyfin-config"},"labels":{"app.kubernetes.io/instance":"jellyfin","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"jellyfin","app.kubernetes.io/version":"10.11.5","helm.sh/chart":"jellyfin-2.7.0"},"name":"jellyfin-config","namespace":"jellyfin"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"5Gi"}},"storageClassName":"qnap-iscsi"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: csi.trident.qnap.io
      volume.kubernetes.io/storage-provisioner: csi.trident.qnap.io
    creationTimestamp: "2026-01-25T02:56:33Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/instance: jellyfin
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: jellyfin
      app.kubernetes.io/version: 10.11.5
      helm.sh/chart: jellyfin-2.7.0
    name: jellyfin-config
    namespace: jellyfin
    resourceVersion: "7956"
    uid: 82e5ded4-41e0-4546-b1f1-1918236c9d08
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: qnap-iscsi
    volumeMode: Filesystem
    volumeName: pvc-82e5ded4-41e0-4546-b1f1-1918236c9d08
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"jellyfin-media","namespace":"jellyfin"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"25Gi"}},"storageClassName":"local-path"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: rpi-7
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2026-01-25T03:05:54Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: jellyfin-media
    namespace: jellyfin
    resourceVersion: "7957"
    uid: 4a14374f-1828-487f-9772-ee3ed0711cdf
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 25Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-4a14374f-1828-487f-9772-ee3ed0711cdf
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 25Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"movies-external","namespace":"jellyfin"},"spec":{"accessModes":["ReadOnlyMany"],"resources":{"requests":{"storage":"2Ti"}},"storageClassName":"smb-movies","volumeName":"jellyfin-movies-external"}}
      pv.kubernetes.io/bind-completed: "yes"
    creationTimestamp: "2026-01-19T04:20:01Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: movies-external
    namespace: jellyfin
    resourceVersion: "7958"
    uid: fdadb46d-dca1-4a8c-837e-51499af78fd5
  spec:
    accessModes:
    - ReadOnlyMany
    resources:
      requests:
        storage: 2Ti
    storageClassName: smb-movies
    volumeMode: Filesystem
    volumeName: jellyfin-movies-external
  status:
    accessModes:
    - ReadOnlyMany
    capacity:
      storage: 2Ti
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"movies-filebot","namespace":"jellyfin"},"spec":{"accessModes":["ReadOnlyMany"],"resources":{"requests":{"storage":"1Ti"}},"storageClassName":"smb-movies","volumeName":"jellyfin-movies-filebot"}}
      pv.kubernetes.io/bind-completed: "yes"
    creationTimestamp: "2026-01-19T04:20:01Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: movies-filebot
    namespace: jellyfin
    resourceVersion: "7959"
    uid: b7b507a3-9e28-469e-9154-bb5f98ed0806
  spec:
    accessModes:
    - ReadOnlyMany
    resources:
      requests:
        storage: 1Ti
    storageClassName: smb-movies
    volumeMode: Filesystem
    volumeName: jellyfin-movies-filebot
  status:
    accessModes:
    - ReadOnlyMany
    capacity:
      storage: 1Ti
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"movies-hd01","namespace":"jellyfin"},"spec":{"accessModes":["ReadOnlyMany"],"resources":{"requests":{"storage":"10Ti"}},"storageClassName":"smb-movies","volumeName":"jellyfin-hd01"}}
      pv.kubernetes.io/bind-completed: "yes"
    creationTimestamp: "2026-01-19T04:47:08Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: movies-hd01
    namespace: jellyfin
    resourceVersion: "7960"
    uid: eccf487d-a200-4255-86aa-7e5139fe002d
  spec:
    accessModes:
    - ReadOnlyMany
    resources:
      requests:
        storage: 10Ti
    storageClassName: smb-movies
    volumeMode: Filesystem
    volumeName: jellyfin-hd01
  status:
    accessModes:
    - ReadOnlyMany
    capacity:
      storage: 10Ti
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"movies-hd02","namespace":"jellyfin"},"spec":{"accessModes":["ReadOnlyMany"],"resources":{"requests":{"storage":"10Ti"}},"storageClassName":"smb-movies","volumeName":"jellyfin-hd02"}}
      pv.kubernetes.io/bind-completed: "yes"
    creationTimestamp: "2026-01-19T04:47:08Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: movies-hd02
    namespace: jellyfin
    resourceVersion: "7961"
    uid: dcf3fa21-e3d3-4bd1-9c61-47e43c6beadc
  spec:
    accessModes:
    - ReadOnlyMany
    resources:
      requests:
        storage: 10Ti
    storageClassName: smb-movies
    volumeMode: Filesystem
    volumeName: jellyfin-hd02
  status:
    accessModes:
    - ReadOnlyMany
    capacity:
      storage: 10Ti
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"movies-hd03","namespace":"jellyfin"},"spec":{"accessModes":["ReadOnlyMany"],"resources":{"requests":{"storage":"10Ti"}},"storageClassName":"smb-movies","volumeName":"jellyfin-hd03"}}
      pv.kubernetes.io/bind-completed: "yes"
    creationTimestamp: "2026-01-19T04:47:08Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: movies-hd03
    namespace: jellyfin
    resourceVersion: "7962"
    uid: 8dc19916-b2a4-4707-b14e-4cc854439924
  spec:
    accessModes:
    - ReadOnlyMany
    resources:
      requests:
        storage: 10Ti
    storageClassName: smb-movies
    volumeMode: Filesystem
    volumeName: jellyfin-hd03
  status:
    accessModes:
    - ReadOnlyMany
    capacity:
      storage: 10Ti
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"movies-hd04","namespace":"jellyfin"},"spec":{"accessModes":["ReadOnlyMany"],"resources":{"requests":{"storage":"10Ti"}},"storageClassName":"smb-movies","volumeName":"jellyfin-hd04"}}
      pv.kubernetes.io/bind-completed: "yes"
    creationTimestamp: "2026-01-19T04:47:08Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: movies-hd04
    namespace: jellyfin
    resourceVersion: "7963"
    uid: fb7b4b88-9004-4c53-88f2-bd3d015c95c5
  spec:
    accessModes:
    - ReadOnlyMany
    resources:
      requests:
        storage: 10Ti
    storageClassName: smb-movies
    volumeMode: Filesystem
    volumeName: jellyfin-hd04
  status:
    accessModes:
    - ReadOnlyMany
    capacity:
      storage: 10Ti
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"movies-hd05","namespace":"jellyfin"},"spec":{"accessModes":["ReadOnlyMany"],"resources":{"requests":{"storage":"10Ti"}},"storageClassName":"smb-movies","volumeName":"jellyfin-hd05"}}
      pv.kubernetes.io/bind-completed: "yes"
    creationTimestamp: "2026-01-19T04:47:08Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: movies-hd05
    namespace: jellyfin
    resourceVersion: "7964"
    uid: 050e9274-2f74-477b-ad27-25993c84318d
  spec:
    accessModes:
    - ReadOnlyMany
    resources:
      requests:
        storage: 10Ti
    storageClassName: smb-movies
    volumeMode: Filesystem
    volumeName: jellyfin-hd05
  status:
    accessModes:
    - ReadOnlyMany
    capacity:
      storage: 10Ti
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"movies-hd06","namespace":"jellyfin"},"spec":{"accessModes":["ReadOnlyMany"],"resources":{"requests":{"storage":"10Ti"}},"storageClassName":"smb-movies","volumeName":"jellyfin-hd06"}}
      pv.kubernetes.io/bind-completed: "yes"
    creationTimestamp: "2026-01-19T04:47:08Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: movies-hd06
    namespace: jellyfin
    resourceVersion: "7965"
    uid: 0ca47933-e824-4469-b404-1754a9aa4d57
  spec:
    accessModes:
    - ReadOnlyMany
    resources:
      requests:
        storage: 10Ti
    storageClassName: smb-movies
    volumeMode: Filesystem
    volumeName: jellyfin-hd06
  status:
    accessModes:
    - ReadOnlyMany
    capacity:
      storage: 10Ti
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"movies-hd07","namespace":"jellyfin"},"spec":{"accessModes":["ReadOnlyMany"],"resources":{"requests":{"storage":"10Ti"}},"storageClassName":"smb-movies","volumeName":"jellyfin-hd07"}}
      pv.kubernetes.io/bind-completed: "yes"
    creationTimestamp: "2026-01-19T04:47:09Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: movies-hd07
    namespace: jellyfin
    resourceVersion: "7966"
    uid: a6a5f177-7768-465f-9dbf-23eecdb323c3
  spec:
    accessModes:
    - ReadOnlyMany
    resources:
      requests:
        storage: 10Ti
    storageClassName: smb-movies
    volumeMode: Filesystem
    volumeName: jellyfin-hd07
  status:
    accessModes:
    - ReadOnlyMany
    capacity:
      storage: 10Ti
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"movies-hd08","namespace":"jellyfin"},"spec":{"accessModes":["ReadOnlyMany"],"resources":{"requests":{"storage":"10Ti"}},"storageClassName":"smb-movies","volumeName":"jellyfin-hd08"}}
      pv.kubernetes.io/bind-completed: "yes"
    creationTimestamp: "2026-01-19T04:47:09Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: movies-hd08
    namespace: jellyfin
    resourceVersion: "7967"
    uid: 48fba53c-1311-4c32-8bc0-78cb893fa9e7
  spec:
    accessModes:
    - ReadOnlyMany
    resources:
      requests:
        storage: 10Ti
    storageClassName: smb-movies
    volumeMode: Filesystem
    volumeName: jellyfin-hd08
  status:
    accessModes:
    - ReadOnlyMany
    capacity:
      storage: 10Ti
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"movies-hd09","namespace":"jellyfin"},"spec":{"accessModes":["ReadOnlyMany"],"resources":{"requests":{"storage":"10Ti"}},"storageClassName":"smb-movies","volumeName":"jellyfin-hd09"}}
      pv.kubernetes.io/bind-completed: "yes"
    creationTimestamp: "2026-01-19T04:47:09Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: movies-hd09
    namespace: jellyfin
    resourceVersion: "7968"
    uid: b0718455-5d34-45fb-8ae3-a94eefb5d3c8
  spec:
    accessModes:
    - ReadOnlyMany
    resources:
      requests:
        storage: 10Ti
    storageClassName: smb-movies
    volumeMode: Filesystem
    volumeName: jellyfin-hd09
  status:
    accessModes:
    - ReadOnlyMany
    capacity:
      storage: 10Ti
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"movies-hd10","namespace":"jellyfin"},"spec":{"accessModes":["ReadOnlyMany"],"resources":{"requests":{"storage":"10Ti"}},"storageClassName":"smb-movies","volumeName":"jellyfin-hd10"}}
      pv.kubernetes.io/bind-completed: "yes"
    creationTimestamp: "2026-01-19T04:47:09Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: movies-hd10
    namespace: jellyfin
    resourceVersion: "7969"
    uid: efdc38f3-f559-4e49-b82d-54fc8174522a
  spec:
    accessModes:
    - ReadOnlyMany
    resources:
      requests:
        storage: 10Ti
    storageClassName: smb-movies
    volumeMode: Filesystem
    volumeName: jellyfin-hd10
  status:
    accessModes:
    - ReadOnlyMany
    capacity:
      storage: 10Ti
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"movies-hd11","namespace":"jellyfin"},"spec":{"accessModes":["ReadOnlyMany"],"resources":{"requests":{"storage":"10Ti"}},"storageClassName":"smb-movies","volumeName":"jellyfin-hd11"}}
      pv.kubernetes.io/bind-completed: "yes"
    creationTimestamp: "2026-01-19T04:47:09Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: movies-hd11
    namespace: jellyfin
    resourceVersion: "7970"
    uid: fc6f7923-34a8-400f-8a57-0f617c66aed1
  spec:
    accessModes:
    - ReadOnlyMany
    resources:
      requests:
        storage: 10Ti
    storageClassName: smb-movies
    volumeMode: Filesystem
    volumeName: jellyfin-hd11
  status:
    accessModes:
    - ReadOnlyMany
    capacity:
      storage: 10Ti
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"movies-hd12","namespace":"jellyfin"},"spec":{"accessModes":["ReadOnlyMany"],"resources":{"requests":{"storage":"10Ti"}},"storageClassName":"smb-movies","volumeName":"jellyfin-hd12"}}
      pv.kubernetes.io/bind-completed: "yes"
    creationTimestamp: "2026-01-19T04:47:09Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: movies-hd12
    namespace: jellyfin
    resourceVersion: "7971"
    uid: 3830cf75-c6b0-4bdd-ae79-973144867d84
  spec:
    accessModes:
    - ReadOnlyMany
    resources:
      requests:
        storage: 10Ti
    storageClassName: smb-movies
    volumeMode: Filesystem
    volumeName: jellyfin-hd12
  status:
    accessModes:
    - ReadOnlyMany
    capacity:
      storage: 10Ti
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
