apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"registry-pvc","namespace":"registry"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}}}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: rpi-1
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2026-01-15T16:33:17Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: registry-pvc
    namespace: registry
    resourceVersion: "7987"
    uid: 88b2e793-cb00-4fe3-9449-20d6043243ea
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-88b2e793-cb00-4fe3-9449-20d6043243ea
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"registry-pvc-qnap","namespace":"registry"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"qnap-iscsi"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: csi.trident.qnap.io
      volume.kubernetes.io/storage-provisioner: csi.trident.qnap.io
    creationTimestamp: "2026-01-25T02:02:20Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: registry-pvc-qnap
    namespace: registry
    resourceVersion: "7988"
    uid: d0757c1c-f40e-489c-b613-eed86f31848c
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: qnap-iscsi
    volumeMode: Filesystem
    volumeName: pvc-d0757c1c-f40e-489c-b613-eed86f31848c
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
