apiVersion: v1
items:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    annotations:
      resource-spec-hash: "1019271535"
    creationTimestamp: "2026-01-22T02:14:11Z"
    generation: 1
    labels:
      controller: eventbus-controller
      eventbus-name: default
      owner-name: default
    name: eventbus-default-stan
    namespace: argo-events
    ownerReferences:
    - apiVersion: argoproj.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: EventBus
      name: default
      uid: 27b873f3-1a79-4fba-bbb4-4268601345c2
    resourceVersion: "10315"
    uid: 3c086c56-7f22-41a4-ae2d-9f3c37272e9d
  spec:
    persistentVolumeClaimRetentionPolicy:
      whenDeleted: Retain
      whenScaled: Retain
    podManagementPolicy: OrderedReady
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        controller: eventbus-controller
        eventbus-name: default
        owner-name: default
    serviceName: eventbus-default-stan-svc
    template:
      metadata:
        labels:
          controller: eventbus-controller
          eventbus-name: default
          owner-name: default
      spec:
        containers:
        - command:
          - /nats-streaming-server
          - -sc
          - /etc/stan-config/stan.conf
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: CLUSTER_ADVERTISE
            value: $(POD_NAME).eventbus-default-stan-svc.$(POD_NAMESPACE).svc
          image: nats-streaming:0.22.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8222
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: stan
          ports:
          - containerPort: 4222
            name: client
            protocol: TCP
          - containerPort: 6222
            name: cluster
            protocol: TCP
          - containerPort: 8222
            name: monitor
            protocol: TCP
          resources:
            requests:
              cpu: "0"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/stan-config
            name: config-volume
          - mountPath: /data/stan
            name: stan-data
        - args:
          - -connz
          - -routez
          - -subz
          - -varz
          - -channelz
          - -serverz
          - http://localhost:8222
          image: natsio/prometheus-nats-exporter:0.8.0
          imagePullPolicy: IfNotPresent
          name: metrics
          ports:
          - containerPort: 7777
            name: metrics
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: config-volume
          projected:
            defaultMode: 420
            sources:
            - configMap:
                items:
                - key: stan-config
                  path: stan.conf
                name: eventbus-default-stan-configmap
            - secret:
                items:
                - key: auth
                  path: auth.conf
                name: eventbus-default-server
        - emptyDir: {}
          name: stan-data
    updateStrategy:
      rollingUpdate:
        partition: 0
      type: RollingUpdate
  status:
    availableReplicas: 3
    collisionCount: 0
    currentReplicas: 3
    currentRevision: eventbus-default-stan-79fcf94ddc
    observedGeneration: 1
    readyReplicas: 3
    replicas: 3
    updateRevision: eventbus-default-stan-79fcf94ddc
    updatedReplicas: 3
kind: List
metadata:
  resourceVersion: ""
