apiVersion: apps/v1
kind: Deployment
metadata:
  name: agents
  namespace: holm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agents
  template:
    metadata:
      labels:
        app: agents
    spec:
      containers:
      - name: agents
        image: registry.holm.svc.cluster.local:5000/agents:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: agents
  namespace: holm
spec:
  type: ClusterIP
  selector:
    app: agents
  ports:
  - port: 8080
    targetPort: 8080
