apiVersion: v1
kind: Pod
metadata:
  name: kaniko-holmos-shell
  namespace: holm
spec:
  nodeSelector:
    kubernetes.io/hostname: rpi-1
  restartPolicy: Never
  initContainers:
  - name: clone-repo
    image: alpine/git:latest
    command:
    - /bin/sh
    - -c
    - |
      git clone --depth 1 --single-branch https://github.com/timholm/HolmOS.git /repo
      cp -r /repo/services/holmos-shell/* /workspace/
      ls -la /workspace/
    volumeMounts:
    - name: workspace
      mountPath: /workspace
    - name: repo
      mountPath: /repo
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--dockerfile=/workspace/Dockerfile"
    - "--context=/workspace"
    - "--destination=registry.holm.svc.cluster.local:5000/holmos-shell:latest"
    - "--insecure"
    - "--skip-tls-verify"
    volumeMounts:
    - name: workspace
      mountPath: /workspace
  volumes:
  - name: workspace
    emptyDir: {}
  - name: repo
    emptyDir: {}
