apiVersion: v1
items:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"name":"immich-postgres","namespace":"immich"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"immich-postgres"}},"serviceName":"immich-postgres","template":{"metadata":{"labels":{"app":"immich-postgres"}},"spec":{"containers":[{"env":[{"name":"PGDATA","value":"/var/lib/postgresql/data/pgdata"}],"envFrom":[{"secretRef":{"name":"immich-postgres-secret"}}],"image":"tensorchord/pgvecto-rs:pg16-v0.2.1","name":"postgres","ports":[{"containerPort":5432}],"volumeMounts":[{"mountPath":"/var/lib/postgresql/data","name":"data"}]}]}},"volumeClaimTemplates":[{"metadata":{"name":"data"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"50Gi"}},"storageClassName":"local-path"}}]}}
    creationTimestamp: "2026-01-19T05:11:53Z"
    generation: 1
    name: immich-postgres
    namespace: immich
    resourceVersion: "43619"
    uid: a6f02aff-234b-4b53-918a-48e18b720284
  spec:
    persistentVolumeClaimRetentionPolicy:
      whenDeleted: Retain
      whenScaled: Retain
    podManagementPolicy: OrderedReady
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: immich-postgres
    serviceName: immich-postgres
    template:
      metadata:
        labels:
          app: immich-postgres
      spec:
        containers:
        - env:
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          envFrom:
          - secretRef:
              name: immich-postgres-secret
          image: tensorchord/pgvecto-rs:pg16-v0.2.1
          imagePullPolicy: IfNotPresent
          name: postgres
          ports:
          - containerPort: 5432
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    updateStrategy:
      rollingUpdate:
        partition: 0
      type: RollingUpdate
    volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: local-path
        volumeMode: Filesystem
      status:
        phase: Pending
  status:
    availableReplicas: 1
    collisionCount: 0
    currentReplicas: 1
    currentRevision: immich-postgres-6bd8bfc5bd
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updateRevision: immich-postgres-6bd8bfc5bd
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
