apiVersion: v1
kind: Pod
metadata:
  name: kaniko-calculator-app
  namespace: holm
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--dockerfile=Dockerfile"
    - "--context=dir:///workspace"
    - "--destination=registry.holm.svc.cluster.local:5000/calculator-app:latest"
    - "--insecure"
    - "--skip-tls-verify"
    volumeMounts:
    - name: workspace
      mountPath: /workspace
  restartPolicy: Never
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  nodeSelector:
    kubernetes.io/hostname: rpi-1
  volumes:
  - name: workspace
    hostPath:
      path: /tmp/calculator-app-build
      type: DirectoryOrCreate
