apiVersion: v1
kind: Pod
metadata:
  name: kaniko-vault
  namespace: holm
spec:
  restartPolicy: Never
  initContainers:
  - name: git-clone
    image: alpine/git:latest
    command:
    - /bin/sh
    - -c
    - |
      git clone https://github.com/timholm/HolmOS.git /tmp/repo
      cp -r /tmp/repo/services/vault/* /workspace/
    volumeMounts:
    - name: workspace
      mountPath: /workspace
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--context=dir:///workspace"
    - "--destination=registry.holm.svc.cluster.local:5000/vault:latest"
    - "--insecure"
    - "--skip-tls-verify"
    - "--cache=true"
    volumeMounts:
    - name: workspace
      mountPath: /workspace
  volumes:
  - name: workspace
    emptyDir: {}
