apiVersion: v1
kind: Pod
metadata:
  name: kaniko-youtube-dl
  namespace: holm
spec:
  initContainers:
  - name: git-clone
    image: alpine/git:latest
    command: ["sh", "-c"]
    args:
    - |
      git clone --depth 1 https://github.com/timholm/HolmOS.git /workspace/repo
      cp -r /workspace/repo/services/youtube-dl/* /workspace/
      ls -la /workspace/
    volumeMounts:
    - name: workspace
      mountPath: /workspace
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--dockerfile=Dockerfile"
    - "--context=dir:///workspace"
    - "--destination=registry.holm.svc.cluster.local:5000/youtube-dl:latest"
    - "--insecure"
    - "--skip-tls-verify"
    volumeMounts:
    - name: workspace
      mountPath: /workspace
  restartPolicy: Never
  volumes:
  - name: workspace
    emptyDir: {}
