apiVersion: v1
kind: Pod
metadata:
  name: kaniko-nova-git
  namespace: holm
spec:
  restartPolicy: Never
  initContainers:
  - name: git-clone
    image: alpine/git:latest
    command:
    - /bin/sh
    - -c
    - |
      git clone https://github.com/timholm/HolmOS.git /repo
      cp -r /repo/services/nova/* /workspace/
      ls -la /workspace/
    volumeMounts:
    - name: workspace
      mountPath: /workspace
    - name: repo
      mountPath: /repo
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--context=dir:///workspace"
    - "--dockerfile=/workspace/Dockerfile"
    - "--destination=registry.holm.svc.cluster.local:5000/nova:latest"
    - "--insecure"
    - "--skip-tls-verify"
    volumeMounts:
    - name: workspace
      mountPath: /workspace
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "2Gi"
        cpu: "2"
  volumes:
  - name: workspace
    emptyDir: {}
  - name: repo
    emptyDir: {}
