apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"minio-data","namespace":"velero"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"100Gi"}},"storageClassName":"nfs-disk2"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: k8s-sigs.io/nfs-disk2
      volume.kubernetes.io/storage-provisioner: k8s-sigs.io/nfs-disk2
    creationTimestamp: "2026-01-28T04:58:52Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: minio-data
    namespace: velero
    resourceVersion: "961481"
    uid: d3d59abb-6e37-4a25-ae42-afd20f436a2b
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 100Gi
    storageClassName: nfs-disk2
    volumeMode: Filesystem
    volumeName: pvc-d3d59abb-6e37-4a25-ae42-afd20f436a2b
  status:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 100Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
